<?php
/** Standalone behavior test for the read-only Content Types admin overview. */
define('ABSPATH', __DIR__ . '/');
$filters = array(); $can = true; $post_objects = array(); $tax_objects = array(); $nonce_checks = 0;
function __($text) { return $text; } function esc_html__($text) { return $text; } function esc_html($text) { return htmlspecialchars((string) $text, ENT_QUOTES, 'UTF-8'); } function esc_attr($text) { return htmlspecialchars((string) $text, ENT_QUOTES, 'UTF-8'); } function esc_url($text) { return (string) $text; } function sanitize_key($key) { return strtolower(preg_replace('/[^a-z0-9_\-]/', '', (string) $key)); } function sanitize_text_field($text) { return (string) $text; } function wp_normalize_path($path) { return str_replace('\\', '/', (string) $path); } function untrailingslashit($path) { return rtrim($path, '/'); }
function add_action() {} function add_filter($hook, $callback) { global $filters; $filters[$hook][] = $callback; } function apply_filters($hook, $value) { global $filters; foreach ($filters[$hook] ?? array() as $callback) $value = $callback($value); return $value; } function wp_unslash($value) { return $value; } function admin_url($path = '') { return 'https://example.test/wp-admin/' . $path; } function add_query_arg($key, $value, $url = '') { if (is_array($key)) { $url = $value; $query = $key; } else { $query = array($key => $value); } return $url . (false === strpos($url, '?') ? '?' : '&') . http_build_query($query); } function wp_json_encode($value) { return json_encode($value); } function is_admin() { return true; } function check_admin_referer() { global $nonce_checks; ++$nonce_checks; }
function current_user_can($cap) { global $can; return $can; } function get_post_type_object($slug) { global $post_objects; return $post_objects[$slug] ?? null; } function get_taxonomy($slug) { global $tax_objects; return $tax_objects[$slug] ?? null; } function get_post_type_archive_link($slug) { return 'project' === $slug ? 'https://example.test/projects/' : false; } function modules_get_source_label($source) { return array('template' => 'Parent Theme', 'stylesheet' => 'Child Theme')[$source] ?? $source; }
function assert_true($value, $message) { if (!$value) throw new Exception($message); }
require dirname(__DIR__) . '/inc/core/modules_admin.php';

$tabs = modules_get_settings_tabs(); assert_true(array_keys($tabs) === array('modules', 'blocks', 'content-types', 'changelog', 'about'), 'Content Types tab order failed');
$post_objects['project'] = (object) array('show_ui' => true, 'cap' => (object) array('edit_posts' => 'edit_projects'));
$tax_objects['topic'] = (object) array('show_ui' => true, 'cap' => (object) array('manage_terms' => 'manage_topics'));
$catalog = array(
    'post_types' => array('entries' => array(
        'template:project' => array('slug' => 'project', 'args' => array('label' => 'Ignored label', 'labels' => array('name' => '<Projects>'), 'public' => true, 'show_in_rest' => false, 'has_archive' => true, 'rewrite' => array('slug' => 'projects'), 'supports' => array('title')), 'source' => 'template', 'file' => '/safe/project.php', 'effective' => false, 'overridden' => true, 'overriding_source' => 'stylesheet', 'registered' => false),
        'stylesheet:project' => array('slug' => 'project', 'args' => array('label' => 'Project', 'public' => false), 'declared_args' => array('label' => 'Project', 'public' => false), 'effective_args' => array('label' => 'Project', 'public' => true), 'source' => 'stylesheet', 'file' => '/safe/child.php', 'effective' => true, 'filtered' => true, 'registered' => true),
        'filter:secret' => array('slug' => 'secret', 'args' => array('label' => 'Secret'), 'source' => 'filter', 'file' => '', 'effective' => true, 'filtered' => true, 'registered' => false),
    )),
    'taxonomies' => array('entries' => array('template:topic' => array('slug' => 'topic', 'args' => array('public' => true, 'hierarchical' => true), 'object_types' => array('project'), 'source' => 'template', 'file' => '/safe/topic.php', 'effective' => true, 'registered' => true))),
    'diagnostics' => array(array('message' => 'Bad <definition>', 'context' => array('origin' => '/safe/<origin>.php', 'taxonomy' => '<topic>', 'slug' => '<slug>', 'post_type' => '<post-type>'))),
);
function lonestar_get_content_type_catalog() { global $catalog; return $catalog; }
ob_start(); modules_render_content_types_tab(); $html = ob_get_clean();
assert_true(false !== strpos($html, 'Post Types') && false !== strpos($html, 'Taxonomies') && 2 === substr_count($html, 'widefat striped'), 'separate widefat tables failed');
assert_true(false !== strpos($html, '&lt;Projects&gt;') && false !== strpos($html, '/safe/project.php'), 'HTML escaping, labels.name precedence, or source path display failed');
assert_true(false !== strpos($html, 'Overridden by Child Theme.') && false !== strpos($html, 'Definition diagnostics'), 'override or diagnostics display failed');
assert_true(false !== strpos($html, 'View posts') && false !== strpos($html, 'View archive') && false !== strpos($html, 'View terms'), 'safe effective capability links failed');
assert_true(false !== strpos($html, 'Filter') && false !== strpos($html, 'Slug exists in WordPress') && false !== strpos($html, 'taxonomy=topic&post_type=project') && false !== strpos($html, '&lt;origin&gt;.php') && false !== strpos($html, '&lt;topic&gt;') && false === strpos($html, '<origin>.php'), 'content-type source, status, contextual link, or diagnostic escaping failed');
assert_true(false !== strpos($html, 'Public: Yes') && false !== strpos($html, 'Showing effective values after filters'), 'filtered entries must display effective configuration without losing declared values');
assert_true(false === strpos($html, '<form') && false === strpos($html, 'nonce') && false === strpos($html, 'checkbox') && false === strpos($html, 'type="submit"'), 'read-only overview rendered a control');
assert_true('Not declared' === modules_get_content_type_argument_display(array(), 'value') && 'Declared empty' === modules_get_content_type_argument_display(array('value' => array()), 'value') && 'Declared null' === modules_get_content_type_argument_display(array('value' => null), 'value'), 'declared empty/null values must not be presented as defaults');
$can = false; ob_start(); modules_render_content_types_tab(); $no_links = ob_get_clean(); assert_true(false === strpos($no_links, 'View posts') && false === strpos($no_links, 'View terms'), 'links must respect capabilities');
$can = true; $post_objects['project']->show_ui = false; $tax_objects['topic']->show_ui = false; ob_start(); modules_render_content_types_tab(); $hidden_ui = ob_get_clean(); assert_true(false === strpos($hidden_ui, 'View posts') && false === strpos($hidden_ui, 'View terms'), 'links must require show_ui');
$post_objects['project']->show_ui = true; $tax_objects['topic']->show_ui = true; $_SERVER['REQUEST_METHOD'] = 'POST'; $_GET['page'] = modules_get_settings_page_slug(); $_POST['lonestar_settings_tab'] = 'content-types'; modules_handle_modules_admin_post(); assert_true(0 === $nonce_checks, 'read-only Content Types POST must stop before nonce and generic write hooks'); unset($_SERVER['REQUEST_METHOD'], $_GET['page'], $_POST['lonestar_settings_tab']);
$_GET['tab'] = 'content-types'; ob_start(); modules_render_modules_admin_page(); $full_page = ob_get_clean(); assert_true(false !== strpos($full_page, 'nav-tab-active') && false === strpos($full_page, '<form'), 'Theme Settings integration must render Content Types outside the settings form'); unset($_GET['tab']);
$catalog = array('post_types' => array('entries' => array()), 'taxonomies' => array('entries' => array()), 'diagnostics' => array()); ob_start(); modules_render_content_types_tab(); $empty = ob_get_clean(); assert_true(false !== strpos($empty, 'No post types were discovered.') && false !== strpos($empty, 'No taxonomies were discovered.'), 'empty state failed');
echo "content-types admin tests passed\n";
